Vagrant.configure("2") do |config|
  config.vm.box = "precise32"
  config.vm.hostname = "myprecise1.box"
  config.vm.network "private_network", type: "dhcp"

  config.vm.provider "virtualbox" do |v|
   v.customize ["modifyvm", :id, "--vram", "24"]
 end
end
